// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JCoincheProtocol.proto

public final class JCoincheProtocol {
  private JCoincheProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JCoincheMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JCoincheMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .JCoincheMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .JCoincheMessage.Type type = 1;</code>
     */
    JCoincheProtocol.JCoincheMessage.Type getType();

    /**
     * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
     */
    boolean hasWelcomeMessage();
    /**
     * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
     */
    JCoincheProtocol.WelcomeMessage getWelcomeMessage();
    /**
     * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
     */
    JCoincheProtocol.WelcomeMessageOrBuilder getWelcomeMessageOrBuilder();

    /**
     * <code>optional .GameStartMessage gameStartMessage = 3;</code>
     */
    boolean hasGameStartMessage();
    /**
     * <code>optional .GameStartMessage gameStartMessage = 3;</code>
     */
    JCoincheProtocol.GameStartMessage getGameStartMessage();
    /**
     * <code>optional .GameStartMessage gameStartMessage = 3;</code>
     */
    JCoincheProtocol.GameStartMessageOrBuilder getGameStartMessageOrBuilder();
  }
  /**
   * Protobuf type {@code JCoincheMessage}
   */
  public static final class JCoincheMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:JCoincheMessage)
      JCoincheMessageOrBuilder {
    // Use JCoincheMessage.newBuilder() to construct.
    private JCoincheMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JCoincheMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JCoincheMessage defaultInstance;
    public static JCoincheMessage getDefaultInstance() {
      return defaultInstance;
    }

    public JCoincheMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JCoincheMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              JCoincheProtocol.JCoincheMessage.Type value = JCoincheProtocol.JCoincheMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              JCoincheProtocol.WelcomeMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = welcomeMessage_.toBuilder();
              }
              welcomeMessage_ = input.readMessage(JCoincheProtocol.WelcomeMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(welcomeMessage_);
                welcomeMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              JCoincheProtocol.GameStartMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = gameStartMessage_.toBuilder();
              }
              gameStartMessage_ = input.readMessage(JCoincheProtocol.GameStartMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gameStartMessage_);
                gameStartMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JCoincheProtocol.internal_static_JCoincheMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JCoincheProtocol.internal_static_JCoincheMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JCoincheProtocol.JCoincheMessage.class, JCoincheProtocol.JCoincheMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<JCoincheMessage> PARSER =
        new com.google.protobuf.AbstractParser<JCoincheMessage>() {
      public JCoincheMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JCoincheMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JCoincheMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code JCoincheMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WELCOME = 0;</code>
       */
      WELCOME(0, 0),
      /**
       * <code>GAME_START = 1;</code>
       */
      GAME_START(1, 1),
      /**
       * <code>TYPE3 = 2;</code>
       */
      TYPE3(2, 2),
      ;

      /**
       * <code>WELCOME = 0;</code>
       */
      public static final int WELCOME_VALUE = 0;
      /**
       * <code>GAME_START = 1;</code>
       */
      public static final int GAME_START_VALUE = 1;
      /**
       * <code>TYPE3 = 2;</code>
       */
      public static final int TYPE3_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return WELCOME;
          case 1: return GAME_START;
          case 2: return TYPE3;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return JCoincheProtocol.JCoincheMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:JCoincheMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private JCoincheProtocol.JCoincheMessage.Type type_;
    /**
     * <code>required .JCoincheMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .JCoincheMessage.Type type = 1;</code>
     */
    public JCoincheProtocol.JCoincheMessage.Type getType() {
      return type_;
    }

    public static final int WELCOMEMESSAGE_FIELD_NUMBER = 2;
    private JCoincheProtocol.WelcomeMessage welcomeMessage_;
    /**
     * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
     */
    public boolean hasWelcomeMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
     */
    public JCoincheProtocol.WelcomeMessage getWelcomeMessage() {
      return welcomeMessage_;
    }
    /**
     * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
     */
    public JCoincheProtocol.WelcomeMessageOrBuilder getWelcomeMessageOrBuilder() {
      return welcomeMessage_;
    }

    public static final int GAMESTARTMESSAGE_FIELD_NUMBER = 3;
    private JCoincheProtocol.GameStartMessage gameStartMessage_;
    /**
     * <code>optional .GameStartMessage gameStartMessage = 3;</code>
     */
    public boolean hasGameStartMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .GameStartMessage gameStartMessage = 3;</code>
     */
    public JCoincheProtocol.GameStartMessage getGameStartMessage() {
      return gameStartMessage_;
    }
    /**
     * <code>optional .GameStartMessage gameStartMessage = 3;</code>
     */
    public JCoincheProtocol.GameStartMessageOrBuilder getGameStartMessageOrBuilder() {
      return gameStartMessage_;
    }

    private void initFields() {
      type_ = JCoincheProtocol.JCoincheMessage.Type.WELCOME;
      welcomeMessage_ = JCoincheProtocol.WelcomeMessage.getDefaultInstance();
      gameStartMessage_ = JCoincheProtocol.GameStartMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, welcomeMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, gameStartMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, welcomeMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, gameStartMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static JCoincheProtocol.JCoincheMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JCoincheProtocol.JCoincheMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JCoincheProtocol.JCoincheMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JCoincheProtocol.JCoincheMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JCoincheProtocol.JCoincheMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JCoincheProtocol.JCoincheMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static JCoincheProtocol.JCoincheMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static JCoincheProtocol.JCoincheMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static JCoincheProtocol.JCoincheMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JCoincheProtocol.JCoincheMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JCoincheProtocol.JCoincheMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JCoincheMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JCoincheMessage)
        JCoincheProtocol.JCoincheMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JCoincheProtocol.internal_static_JCoincheMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JCoincheProtocol.internal_static_JCoincheMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JCoincheProtocol.JCoincheMessage.class, JCoincheProtocol.JCoincheMessage.Builder.class);
      }

      // Construct using JCoincheProtocol.JCoincheMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWelcomeMessageFieldBuilder();
          getGameStartMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = JCoincheProtocol.JCoincheMessage.Type.WELCOME;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (welcomeMessageBuilder_ == null) {
          welcomeMessage_ = JCoincheProtocol.WelcomeMessage.getDefaultInstance();
        } else {
          welcomeMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (gameStartMessageBuilder_ == null) {
          gameStartMessage_ = JCoincheProtocol.GameStartMessage.getDefaultInstance();
        } else {
          gameStartMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JCoincheProtocol.internal_static_JCoincheMessage_descriptor;
      }

      public JCoincheProtocol.JCoincheMessage getDefaultInstanceForType() {
        return JCoincheProtocol.JCoincheMessage.getDefaultInstance();
      }

      public JCoincheProtocol.JCoincheMessage build() {
        JCoincheProtocol.JCoincheMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public JCoincheProtocol.JCoincheMessage buildPartial() {
        JCoincheProtocol.JCoincheMessage result = new JCoincheProtocol.JCoincheMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (welcomeMessageBuilder_ == null) {
          result.welcomeMessage_ = welcomeMessage_;
        } else {
          result.welcomeMessage_ = welcomeMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (gameStartMessageBuilder_ == null) {
          result.gameStartMessage_ = gameStartMessage_;
        } else {
          result.gameStartMessage_ = gameStartMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JCoincheProtocol.JCoincheMessage) {
          return mergeFrom((JCoincheProtocol.JCoincheMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JCoincheProtocol.JCoincheMessage other) {
        if (other == JCoincheProtocol.JCoincheMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasWelcomeMessage()) {
          mergeWelcomeMessage(other.getWelcomeMessage());
        }
        if (other.hasGameStartMessage()) {
          mergeGameStartMessage(other.getGameStartMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JCoincheProtocol.JCoincheMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JCoincheProtocol.JCoincheMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private JCoincheProtocol.JCoincheMessage.Type type_ = JCoincheProtocol.JCoincheMessage.Type.WELCOME;
      /**
       * <code>required .JCoincheMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .JCoincheMessage.Type type = 1;</code>
       */
      public JCoincheProtocol.JCoincheMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .JCoincheMessage.Type type = 1;</code>
       */
      public Builder setType(JCoincheProtocol.JCoincheMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .JCoincheMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = JCoincheProtocol.JCoincheMessage.Type.WELCOME;
        onChanged();
        return this;
      }

      private JCoincheProtocol.WelcomeMessage welcomeMessage_ = JCoincheProtocol.WelcomeMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          JCoincheProtocol.WelcomeMessage, JCoincheProtocol.WelcomeMessage.Builder, JCoincheProtocol.WelcomeMessageOrBuilder> welcomeMessageBuilder_;
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public boolean hasWelcomeMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public JCoincheProtocol.WelcomeMessage getWelcomeMessage() {
        if (welcomeMessageBuilder_ == null) {
          return welcomeMessage_;
        } else {
          return welcomeMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public Builder setWelcomeMessage(JCoincheProtocol.WelcomeMessage value) {
        if (welcomeMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          welcomeMessage_ = value;
          onChanged();
        } else {
          welcomeMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public Builder setWelcomeMessage(
          JCoincheProtocol.WelcomeMessage.Builder builderForValue) {
        if (welcomeMessageBuilder_ == null) {
          welcomeMessage_ = builderForValue.build();
          onChanged();
        } else {
          welcomeMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public Builder mergeWelcomeMessage(JCoincheProtocol.WelcomeMessage value) {
        if (welcomeMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              welcomeMessage_ != JCoincheProtocol.WelcomeMessage.getDefaultInstance()) {
            welcomeMessage_ =
              JCoincheProtocol.WelcomeMessage.newBuilder(welcomeMessage_).mergeFrom(value).buildPartial();
          } else {
            welcomeMessage_ = value;
          }
          onChanged();
        } else {
          welcomeMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public Builder clearWelcomeMessage() {
        if (welcomeMessageBuilder_ == null) {
          welcomeMessage_ = JCoincheProtocol.WelcomeMessage.getDefaultInstance();
          onChanged();
        } else {
          welcomeMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public JCoincheProtocol.WelcomeMessage.Builder getWelcomeMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getWelcomeMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      public JCoincheProtocol.WelcomeMessageOrBuilder getWelcomeMessageOrBuilder() {
        if (welcomeMessageBuilder_ != null) {
          return welcomeMessageBuilder_.getMessageOrBuilder();
        } else {
          return welcomeMessage_;
        }
      }
      /**
       * <code>optional .WelcomeMessage welcomeMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          JCoincheProtocol.WelcomeMessage, JCoincheProtocol.WelcomeMessage.Builder, JCoincheProtocol.WelcomeMessageOrBuilder> 
          getWelcomeMessageFieldBuilder() {
        if (welcomeMessageBuilder_ == null) {
          welcomeMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              JCoincheProtocol.WelcomeMessage, JCoincheProtocol.WelcomeMessage.Builder, JCoincheProtocol.WelcomeMessageOrBuilder>(
                  getWelcomeMessage(),
                  getParentForChildren(),
                  isClean());
          welcomeMessage_ = null;
        }
        return welcomeMessageBuilder_;
      }

      private JCoincheProtocol.GameStartMessage gameStartMessage_ = JCoincheProtocol.GameStartMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          JCoincheProtocol.GameStartMessage, JCoincheProtocol.GameStartMessage.Builder, JCoincheProtocol.GameStartMessageOrBuilder> gameStartMessageBuilder_;
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public boolean hasGameStartMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public JCoincheProtocol.GameStartMessage getGameStartMessage() {
        if (gameStartMessageBuilder_ == null) {
          return gameStartMessage_;
        } else {
          return gameStartMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public Builder setGameStartMessage(JCoincheProtocol.GameStartMessage value) {
        if (gameStartMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gameStartMessage_ = value;
          onChanged();
        } else {
          gameStartMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public Builder setGameStartMessage(
          JCoincheProtocol.GameStartMessage.Builder builderForValue) {
        if (gameStartMessageBuilder_ == null) {
          gameStartMessage_ = builderForValue.build();
          onChanged();
        } else {
          gameStartMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public Builder mergeGameStartMessage(JCoincheProtocol.GameStartMessage value) {
        if (gameStartMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              gameStartMessage_ != JCoincheProtocol.GameStartMessage.getDefaultInstance()) {
            gameStartMessage_ =
              JCoincheProtocol.GameStartMessage.newBuilder(gameStartMessage_).mergeFrom(value).buildPartial();
          } else {
            gameStartMessage_ = value;
          }
          onChanged();
        } else {
          gameStartMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public Builder clearGameStartMessage() {
        if (gameStartMessageBuilder_ == null) {
          gameStartMessage_ = JCoincheProtocol.GameStartMessage.getDefaultInstance();
          onChanged();
        } else {
          gameStartMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public JCoincheProtocol.GameStartMessage.Builder getGameStartMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getGameStartMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      public JCoincheProtocol.GameStartMessageOrBuilder getGameStartMessageOrBuilder() {
        if (gameStartMessageBuilder_ != null) {
          return gameStartMessageBuilder_.getMessageOrBuilder();
        } else {
          return gameStartMessage_;
        }
      }
      /**
       * <code>optional .GameStartMessage gameStartMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          JCoincheProtocol.GameStartMessage, JCoincheProtocol.GameStartMessage.Builder, JCoincheProtocol.GameStartMessageOrBuilder> 
          getGameStartMessageFieldBuilder() {
        if (gameStartMessageBuilder_ == null) {
          gameStartMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              JCoincheProtocol.GameStartMessage, JCoincheProtocol.GameStartMessage.Builder, JCoincheProtocol.GameStartMessageOrBuilder>(
                  getGameStartMessage(),
                  getParentForChildren(),
                  isClean());
          gameStartMessage_ = null;
        }
        return gameStartMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:JCoincheMessage)
    }

    static {
      defaultInstance = new JCoincheMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:JCoincheMessage)
  }

  public interface WelcomeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WelcomeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code WelcomeMessage}
   */
  public static final class WelcomeMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:WelcomeMessage)
      WelcomeMessageOrBuilder {
    // Use WelcomeMessage.newBuilder() to construct.
    private WelcomeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WelcomeMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WelcomeMessage defaultInstance;
    public static WelcomeMessage getDefaultInstance() {
      return defaultInstance;
    }

    public WelcomeMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WelcomeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JCoincheProtocol.internal_static_WelcomeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JCoincheProtocol.internal_static_WelcomeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JCoincheProtocol.WelcomeMessage.class, JCoincheProtocol.WelcomeMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<WelcomeMessage> PARSER =
        new com.google.protobuf.AbstractParser<WelcomeMessage>() {
      public WelcomeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WelcomeMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WelcomeMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static JCoincheProtocol.WelcomeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JCoincheProtocol.WelcomeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JCoincheProtocol.WelcomeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JCoincheProtocol.WelcomeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JCoincheProtocol.WelcomeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JCoincheProtocol.WelcomeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static JCoincheProtocol.WelcomeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static JCoincheProtocol.WelcomeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static JCoincheProtocol.WelcomeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JCoincheProtocol.WelcomeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JCoincheProtocol.WelcomeMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WelcomeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WelcomeMessage)
        JCoincheProtocol.WelcomeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JCoincheProtocol.internal_static_WelcomeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JCoincheProtocol.internal_static_WelcomeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JCoincheProtocol.WelcomeMessage.class, JCoincheProtocol.WelcomeMessage.Builder.class);
      }

      // Construct using JCoincheProtocol.WelcomeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JCoincheProtocol.internal_static_WelcomeMessage_descriptor;
      }

      public JCoincheProtocol.WelcomeMessage getDefaultInstanceForType() {
        return JCoincheProtocol.WelcomeMessage.getDefaultInstance();
      }

      public JCoincheProtocol.WelcomeMessage build() {
        JCoincheProtocol.WelcomeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public JCoincheProtocol.WelcomeMessage buildPartial() {
        JCoincheProtocol.WelcomeMessage result = new JCoincheProtocol.WelcomeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JCoincheProtocol.WelcomeMessage) {
          return mergeFrom((JCoincheProtocol.WelcomeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JCoincheProtocol.WelcomeMessage other) {
        if (other == JCoincheProtocol.WelcomeMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JCoincheProtocol.WelcomeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JCoincheProtocol.WelcomeMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WelcomeMessage)
    }

    static {
      defaultInstance = new WelcomeMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WelcomeMessage)
  }

  public interface GameStartMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameStartMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>optional int32 playerId = 2;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>optional int32 playerId = 2;</code>
     */
    int getPlayerId();

    /**
     * <code>optional int32 teamId = 3;</code>
     */
    boolean hasTeamId();
    /**
     * <code>optional int32 teamId = 3;</code>
     */
    int getTeamId();

    /**
     * <code>optional int32 partnerId = 4;</code>
     */
    boolean hasPartnerId();
    /**
     * <code>optional int32 partnerId = 4;</code>
     */
    int getPartnerId();
  }
  /**
   * Protobuf type {@code GameStartMessage}
   */
  public static final class GameStartMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GameStartMessage)
      GameStartMessageOrBuilder {
    // Use GameStartMessage.newBuilder() to construct.
    private GameStartMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameStartMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameStartMessage defaultInstance;
    public static GameStartMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GameStartMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameStartMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              token_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              teamId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              partnerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JCoincheProtocol.internal_static_GameStartMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JCoincheProtocol.internal_static_GameStartMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JCoincheProtocol.GameStartMessage.class, JCoincheProtocol.GameStartMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GameStartMessage> PARSER =
        new com.google.protobuf.AbstractParser<GameStartMessage>() {
      public GameStartMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameStartMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameStartMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>optional string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerId_;
    /**
     * <code>optional int32 playerId = 2;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 playerId = 2;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int TEAMID_FIELD_NUMBER = 3;
    private int teamId_;
    /**
     * <code>optional int32 teamId = 3;</code>
     */
    public boolean hasTeamId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 teamId = 3;</code>
     */
    public int getTeamId() {
      return teamId_;
    }

    public static final int PARTNERID_FIELD_NUMBER = 4;
    private int partnerId_;
    /**
     * <code>optional int32 partnerId = 4;</code>
     */
    public boolean hasPartnerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 partnerId = 4;</code>
     */
    public int getPartnerId() {
      return partnerId_;
    }

    private void initFields() {
      token_ = "";
      playerId_ = 0;
      teamId_ = 0;
      partnerId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, teamId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, partnerId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, teamId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, partnerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static JCoincheProtocol.GameStartMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JCoincheProtocol.GameStartMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JCoincheProtocol.GameStartMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JCoincheProtocol.GameStartMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JCoincheProtocol.GameStartMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JCoincheProtocol.GameStartMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static JCoincheProtocol.GameStartMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static JCoincheProtocol.GameStartMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static JCoincheProtocol.GameStartMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JCoincheProtocol.GameStartMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JCoincheProtocol.GameStartMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameStartMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameStartMessage)
        JCoincheProtocol.GameStartMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JCoincheProtocol.internal_static_GameStartMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JCoincheProtocol.internal_static_GameStartMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JCoincheProtocol.GameStartMessage.class, JCoincheProtocol.GameStartMessage.Builder.class);
      }

      // Construct using JCoincheProtocol.GameStartMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        teamId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        partnerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JCoincheProtocol.internal_static_GameStartMessage_descriptor;
      }

      public JCoincheProtocol.GameStartMessage getDefaultInstanceForType() {
        return JCoincheProtocol.GameStartMessage.getDefaultInstance();
      }

      public JCoincheProtocol.GameStartMessage build() {
        JCoincheProtocol.GameStartMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public JCoincheProtocol.GameStartMessage buildPartial() {
        JCoincheProtocol.GameStartMessage result = new JCoincheProtocol.GameStartMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.teamId_ = teamId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.partnerId_ = partnerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JCoincheProtocol.GameStartMessage) {
          return mergeFrom((JCoincheProtocol.GameStartMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JCoincheProtocol.GameStartMessage other) {
        if (other == JCoincheProtocol.GameStartMessage.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasTeamId()) {
          setTeamId(other.getTeamId());
        }
        if (other.hasPartnerId()) {
          setPartnerId(other.getPartnerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JCoincheProtocol.GameStartMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JCoincheProtocol.GameStartMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      private int playerId_ ;
      /**
       * <code>optional int32 playerId = 2;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0;
        onChanged();
        return this;
      }

      private int teamId_ ;
      /**
       * <code>optional int32 teamId = 3;</code>
       */
      public boolean hasTeamId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 teamId = 3;</code>
       */
      public int getTeamId() {
        return teamId_;
      }
      /**
       * <code>optional int32 teamId = 3;</code>
       */
      public Builder setTeamId(int value) {
        bitField0_ |= 0x00000004;
        teamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 teamId = 3;</code>
       */
      public Builder clearTeamId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        teamId_ = 0;
        onChanged();
        return this;
      }

      private int partnerId_ ;
      /**
       * <code>optional int32 partnerId = 4;</code>
       */
      public boolean hasPartnerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 partnerId = 4;</code>
       */
      public int getPartnerId() {
        return partnerId_;
      }
      /**
       * <code>optional int32 partnerId = 4;</code>
       */
      public Builder setPartnerId(int value) {
        bitField0_ |= 0x00000008;
        partnerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 partnerId = 4;</code>
       */
      public Builder clearPartnerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        partnerId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GameStartMessage)
    }

    static {
      defaultInstance = new GameStartMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GameStartMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JCoincheMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JCoincheMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WelcomeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WelcomeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameStartMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameStartMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026JCoincheProtocol.proto\"\274\001\n\017JCoincheMes" +
      "sage\022#\n\004type\030\001 \002(\0162\025.JCoincheMessage.Typ" +
      "e\022\'\n\016welcomeMessage\030\002 \001(\0132\017.WelcomeMessa" +
      "ge\022+\n\020gameStartMessage\030\003 \001(\0132\021.GameStart" +
      "Message\".\n\004Type\022\013\n\007WELCOME\020\000\022\016\n\nGAME_STA" +
      "RT\020\001\022\t\n\005TYPE3\020\002\"!\n\016WelcomeMessage\022\017\n\007mes" +
      "sage\030\001 \001(\t\"V\n\020GameStartMessage\022\r\n\005token\030" +
      "\001 \001(\t\022\020\n\010playerId\030\002 \001(\005\022\016\n\006teamId\030\003 \001(\005\022" +
      "\021\n\tpartnerId\030\004 \001(\005B\022B\020JCoincheProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JCoincheMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JCoincheMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_JCoincheMessage_descriptor,
        new java.lang.String[] { "Type", "WelcomeMessage", "GameStartMessage", });
    internal_static_WelcomeMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WelcomeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_WelcomeMessage_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GameStartMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GameStartMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameStartMessage_descriptor,
        new java.lang.String[] { "Token", "PlayerId", "TeamId", "PartnerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
